Update w_loss to a variable.
This is necessary because before the following
error message occured
    InaccessibleTensorError: <tf.Tensor 'cond_3/Identity:0' shape=(3,) dtype=float32> is out of scope and cannot be used here. Use return values, explicit Python locals or TensorFlow collections to access it.
    Please see https://www.tensorflow.org/guide/function#all_outputs_of_a_tffunction_must_be_return_values for more information.

Changing to a variable removes this issue.